/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ro.go.adrhc.springkafkastreams.infrastructure.topologies.payments.reports.messages;

/** commands protocol */
@org.apache.avro.specific.AvroGenerated
public interface CommandsProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"CommandsProtocol\",\"namespace\":\"ro.go.adrhc.springkafkastreams.infrastructure.topologies.payments.reports.messages\",\"doc\":\"commands protocol\",\"types\":[{\"type\":\"record\",\"name\":\"Command\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"parameters\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  /** commands protocol */
  public interface Callback extends CommandsProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = ro.go.adrhc.springkafkastreams.infrastructure.topologies.payments.reports.messages.CommandsProtocol.PROTOCOL;
  }
}