/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ro.go.adrhc.springkafkastreams.topologies.exceeds.daily.messages;

/** daily exceeds protocol */
@org.apache.avro.specific.AvroGenerated
public interface DailyExceedsProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"DailyExceedsProtocol\",\"namespace\":\"ro.go.adrhc.springkafkastreams.topologies.exceeds.daily.messages\",\"doc\":\"daily exceeds protocol\",\"types\":[{\"type\":\"record\",\"name\":\"DailyTotalSpent\",\"fields\":[{\"name\":\"clientId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"time\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"amount\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"DailyExceeded\",\"fields\":[{\"name\":\"dailyMaxAmount\",\"type\":\"int\"},{\"name\":\"dailyTotalSpent\",\"type\":\"DailyTotalSpent\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  /** daily exceeds protocol */
  public interface Callback extends DailyExceedsProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = ro.go.adrhc.springkafkastreams.topologies.exceeds.daily.messages.DailyExceedsProtocol.PROTOCOL;
  }
}